### ISSUE TITLE
Could not find any cell

### ISSUE THREAD

**Issue by joerichter-stash** [falkenber9/falcon#5]
Hello,

i would like to use the FalconGui for a SDR tech-demo, but unfortunately i am not able to find the cell in FalconGui.

To find the cell frequency and ID i used: https://github.com/JiaoXianjun/LTE-Cell-Scanner with an RTL-SDR:
with the following command:
```
CellSearch -s 1810e6 -e 1830e6 -p 1
```
Output:
```
Detected a FDD cell! At freqeuncy 1815.2MHz, try 0
    cell ID: 376
     PSS ID: 1
    RX power level: -18.6699 dB
    residual frequency offset: -11389.2 Hz
                     k_factor: 1.00001
```

For FalconGui i used a Ettus B200, that i previously tested with Gqrx.
I used the frequency and CID as input for FalconGui and got the following log:
```
QMetaObject::connectSlotsByName: No matching signal for on_actionDownlink_Plots_changed()
RF_Freq:  1.8152e+09
Creating Phy
SubframeWorkerThread ready
Spectrum View on
Opening RF device with 1 RX antennas...
[INFO] [UHD] linux; GNU C++ version 9.3.0; Boost_107100; UHD_3.15.0.0-release
[INFO] [B200] Loading firmware image: /usr/share/uhd/images/usrp_b200_fw.hex...
Opening USRP with args: type=b200,master_clock_rate=30.72e6
[INFO] [B200] Detected Device: B200
[INFO] [B200] Loading FPGA image: /usr/share/uhd/images/usrp_b200_fpga.bin...
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Detecting internal GPSDO.... 
[INFO] [GPS] No GPSDO found
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 30.720000 MHz... 
[INFO] [B200] Actually got clock rate 30.720000 MHz.
Starting AGC thread...
Tunning receiver to 1.8152e+09 Hz
Searching for cell...
Could not find any cell in this frequency
Cell not found after 0 trials
Searching for cell...
Could not find any cell in this frequency
Cell not found after 1 trials
Searching for cell...
Could not find any cell in this frequency
Cell not found after 2 trials
EyeCore: Exiting...
SubframeWorkerThread ended
Destroyed Phy
```

I have also tried this with several other Cells i have found with LTE-Cell-Scanner. A few times FalconGui found some PDCCH but discarded them without further information.

Can you help me with further information, what i am missing for this setup or how to debug it? May it be related to the usage of a B200?

Best regards,
Joe

**Comment by falkenber9** [comment]
Hi Joe,

could you please verify if the cell is found by the ``cell_search`` application that comes with srsLTE? If srsLTE is built as a subproject, you can find the binary in ``<build-dir>/srsLTE-build/lib/examples``.

Best regards,
Robert

**Comment by joerichter-stash** [comment]
Hi Robert,

Thanks for your help. `cell_search` from srsLTE solved the issue. 

I noticed further, that if the base station signal is too weak (in my case < ~ -40dBm) the cell also could not be found in FalconGUI. But i guess this is normal behavior.

Thank you and best regards,
Joe
